name: CI

on: [push, pull_request]

permissions: "read-all"

defaults:
  run:
    shell: bash

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Check packages
        run: |
          python3.7 -m pip install --index-url 'https://:2023-10-02T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/' pip setuptools wheel twine rstcheck;
          python3.7 setup.py sdist bdist_wheel;
          rstcheck README.rst CHANGES.rst
          python3.7 -m twine check dist/*
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [macos-latest, windows-latest, ubuntu-latest]
        experimental: [false]
        nox-session: ['']
        exclude:
          # GitHub Actions dropped support for Python 2.7 and 3.7 in Ubuntu 22.04
          - python-version: "2.7"
            os: ubuntu-latest
          - python-version: "3.6"
            os: ubuntu-latest
          # Python 3.7 does not fully support OpenSSL 3, the default on Ubuntu 22.04
          # https://bugs.python.org/issue38820
          - python-version: "3.7"
            os: ubuntu-latest
          - python-version: "2.7"
            os: macos-latest
        include:
          - python-version: "2.7"
            os: ubuntu-20.04
            experimental: false
            nox-session: ''
          - python-version: "3.6"
            os: ubuntu-20.04
            experimental: false
            nox-session: ''
          - python-version: "3.7"
            os: ubuntu-20.04
            experimental: false
            nox-session: ''
          - python-version: "pypy3.9"
            os: ubuntu-latest
            experimental: false
            nox-session: test-pypy
          - python-version: "pypy2.7"
            os: ubuntu-20.04
            experimental: false
            nox-session: test-pypy
          - python-version: "2.7"
            os: ubuntu-latest
            experimental: false
            nox-session: google_brotli-2.7
          - python-version: "3.x"
            os: ubuntu-latest
            experimental: false
            nox-session: google_brotli-3
          - python-version: "2.7"
            os: ubuntu-latest
            experimental: false
            nox-session: app_engine
          - python-version: 3.11
            os: ubuntu-latest
            experimental: true
            nox-session: test-3.11

    runs-on: ${{ matrix.os }}
    name: ${{ fromJson('{"macos-latest":"macOS","windows-latest":"Windows","ubuntu-20.04":"Ubuntu 20.04","ubuntu-latest":"Ubuntu"}')[matrix.os] }} ${{ matrix.python-version }} ${{ matrix.nox-session}}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set Up Python 3 to run nox
        if: matrix.python-version == '2.7' || matrix.python-version == 'pypy2.7'
        uses: actions/setup-python@v4
        with:
          python-version: "3"

      - if: matrix.python-version == '2.7' || matrix.python-version == 'pypy2.7'
        name: Install Dependencies
        run: python -m pip install --index-url 'https://:2023-10-02T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/' --upgrade pip setuptools nox 'virtualenv<20.22.0'

      - if: matrix.python-version != '2.7' && matrix.python-version != 'pypy2.7'
        name: Install Dependencies
        run: python -m pip install --index-url 'https://:2023-10-02T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/' --upgrade pip setuptools nox

      - name: Run Tests
        run: ./ci/run_tests.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          NOX_SESSION: ${{ matrix.nox-session }}


  coverage:
    if: always()
    runs-on: "ubuntu-latest"
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: "Use latest Python so it understands all syntax"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Install coverage"
        run: "python -m pip install --index-url 'https://:2023-10-02T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/' --upgrade coverage"

      - name: "Download coverage data"
        uses: actions/download-artifact@v2
        with:
          name: coverage-data

      - name: "Combine & check coverage"
        run: |
          python -m coverage combine
          python -m coverage html --skip-covered --skip-empty
          python -m coverage report --ignore-errors --show-missing --fail-under=100
