name: Downstream

on:
  pull_request:
    paths:
      - "src/urllib3/_version.py"

permissions: "read-all"

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        downstream: [botocore, requests]

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: python -m pip install --index-url 'https://:2023-10-02T00:00:00.000000Z@time-machines-pypi.sealsecurity.io/' --upgrade nox
      - name: Run downstream tests
        run: nox -s downstream_${{ matrix.downstream }}-${{ matrix.python-version }}
